### ISSUE TITLE
Change `import` to the modified file names

### ISSUE THREAD

**Issue by thanhtoantnt** [cl2089/etherscan-contract-crawler#9]
Currently, when a project is crawled, the file name is changed, e.g., `07_09_Zapper.sol`. However, the `import` files are not updated accordingly, e.g., it is still `import "openzeppelin-contracts/token/ERC20/extensions/IERC20Metadata.sol";`, even the file `IERC20Metada.sol` is crawled in the repository.

If I remember correctly, this problem does not exist in the older version.

Command to reproduce: `python contract_crawler.py --url https://etherscan.io/address/0xD248B30A3207A766d318C7A87F5Cf334A439446D#code` and check the `import` in the files.

**Comment by cassc** [comment]
The perfix, eg., `07_09_` is added to allow contracts with same file names. You can use the [script](https://github.com/cl2089/etherscan-contract-crawler/blob/main/fix-imports-solidity.py) to fix the imported files to make the solidity project compilable.

**Comment by thanhtoantnt** [comment]
thank you, @cl2089. I am clear now.
